# Generated by Django 5.0.8 on 2024-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inimigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('super_poder', models.CharField(max_length=100)),
                ('grau_de_perigo', models.CharField(max_length=50)),
                ('capturado', models.BooleanField(default=False)),
                ('imagem', models.CharField(max_length=100)),
            ],
        ),
    ]
