# Generated by Django 5.0.8 on 2024-08-13 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0002_inimigos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamentos',
            old_name='imagem',
            new_name='usuario_atual',
        ),
        migrations.RemoveField(
            model_name='inimigos',
            name='imagem',
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='localizacao',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inimigos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
