# Generated by Django 5.0.8 on 2024-08-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0003_rename_imagem_equipamentos_usuario_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='localizacao',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
