# Generated by Django 5.0.8 on 2024-08-20 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0004_alter_equipamentos_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inimigos',
            name='nome',
        ),
        migrations.AddField(
            model_name='inimigos',
            name='armas',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='inimigos',
            name='data_captura',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inimigos',
            name='descricao',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='inimigos',
            name='localizacao',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='inimigos',
            name='nome_inimigo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='inimigos',
            name='sexo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='inimigos',
            name='grau_de_perigo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='inimigos',
            name='super_poder',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
