# Generated by Django 5.0.8 on 2024-08-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0005_remove_inimigos_nome_inimigos_armas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inimigos',
            name='descricao',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
