# Generated by Django 5.0.8 on 2024-08-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0006_alter_inimigos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inimigos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
