# Generated by Django 5.0.8 on 2024-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0008_remove_inimigos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inimigos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/gerenciador_industriawayne/css/images'),
        ),
    ]
