# Generated by Django 5.0.8 on 2024-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0010_alter_inimigos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
