# Generated by Django 5.0.8 on 2024-09-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0011_equipamentos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_meta', models.CharField(default=None, max_length=100)),
                ('responsavel', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
