# Generated by Django 5.0.8 on 2024-09-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0012_metas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamentos',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='inimigos',
            options={'verbose_name': 'Inimigo', 'verbose_name_plural': 'Inimigos'},
        ),
        migrations.AlterModelOptions(
            name='metas',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
    ]
