# Generated by Django 5.0.8 on 2024-09-10 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0013_alter_equipamentos_options_alter_inimigos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='data_prazo',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='metas',
            name='descricao',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='metas',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
