# Generated by Django 5.0.8 on 2024-09-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_industriawayne', '0014_metas_data_prazo_metas_descricao_metas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='localizacao',
            field=models.CharField(choices=[('Garagem Batcaverna', 'Garagem Batcaverna'), ('Armário 01', 'Armário 01'), ('Armário 02', 'Armário 02'), ('Oficina', 'Oficina'), ('Emprestado Polícia', 'Emprestado Polícia'), ('Com o usuário', 'Com o usuário')], max_length=25),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='status',
            field=models.CharField(choices=[('Em uso', 'Em uso'), ('Manutenção', 'Manutenção')], max_length=12),
        ),
        migrations.AlterField(
            model_name='inimigos',
            name='grau_de_perigo',
            field=models.CharField(choices=[('Baixa Periculosidade', 'Baixa Periculosidade'), ('Média Periculosidade', 'Média Periculosidade'), ('Alta Periculosidade', 'Alta Periculosidade')], max_length=22),
        ),
        migrations.AlterField(
            model_name='inimigos',
            name='localizacao',
            field=models.CharField(choices=[('Foragido', 'Foragido'), ('Prisão Gothan City', 'Prisão Gothan City'), ('Prisão Federal', 'Prisão Federal')], max_length=25),
        ),
        migrations.AlterField(
            model_name='inimigos',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misógeno', 'Misógeno'), ('Extraterrestre', 'Extraterrestre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='metas',
            name='status',
            field=models.CharField(choices=[('Aguardando data/prazo', 'Aguardando data/prazo'), ('Concluída', 'Concluída')], max_length=25),
        ),
    ]
